---
- name: Provision AWS infrastructure
  hosts: localhost
  gather_facts: false
  vars:
    ami: ami-0440e5026412ff23f # Ubuntu22.04@eu-north-1
    app_name: myboxfuse
    user_name: ubuntu
    key_file: "~/.ssh/{{ app_name }}.pem"
  tasks:
    - name: Create SSH key pair
      ec2_key: "name={{ app_name }}"
      register: ec2_key_output

    - name: Save SSH private key
      copy:
        content: "{{ ec2_key_output.key.private_key }}"
        dest: "{{ key_file }}"
        mode: 0600
        
    - name: Create SSH security group
      ec2_group:
        name: "{{ app_name }}-ssh"
        rules:
          - proto: tcp
            ports: 22
            cidr_ip: 0.0.0.0/0
        
    - name: Create Tomcat security group
      ec2_group:
        name: "{{ app_name }}-tomcat"
        rules:
          - proto: tcp
            ports: 8080
            cidr_ip: 0.0.0.0/0

    - name: Provision an EC2 builder node
      ec2_instance:
        name: Builder
        state: started
        instance_role: ecr_admin
        wait: true
        key_name: "{{ app_name }}"
        instance_type: t3.micro
        security_group: "{{ app_name }}-ssh"
        network:
          assign_public_ip: true
        image_id: "{{ ami }}"
        tags:
          Environment: build
      register: builder

    - name: Add builder instance public IPs to the build group
      add_host:
        hostname: "{{ builder.public_ip_address[0] }}"
        groups: build
        ansible_user: "{{ user_name }}"
        ansible_ssh_private_key_file: "{{ key_file }}"

    - name: Provision an EC2 runner node
      ec2_instance:
        name: Runner
        state: started
        instance_role: ecr_admin
        wait: true
        key_name: "{{ app_name }}"
        instance_type: t3.micro
        security_groups:
          - "{{ app_name }}-ssh"
          - "{{ app_name }}-tomcat"
        network:
          assign_public_ip: true
        image_id: "{{ ami }}"
        tags:
          Environment: run
      register: runner

    - name: Add runner instance public IPs to the run group
      add_host:
        hostname: "{{ runner.public_ip_address[0] }}"
        groups: run
        ansible_user: "{{ user_name }}"
        ansible_ssh_private_key_file: "{{ key_file }}"

    - name: Ensure the repository is present
      ecs_ecr: "name={{ app_name }}"
      register: repo_facts

    - name: Get ECR password
      command: aws ecr get-login-password --region eu-north-1
      register: repo_password

- name: Prepare nodes
  hosts:
    - build
    - run
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name:
          - docker.io
          - python3-docker
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

- name: Build the App
  hosts: build
  become: yes
  vars:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    repo_path: /var/repo
    app: hello-1.0
    war_path: "{{ repo_path }}/target/{{ app }}.war"
    file_to_change: src/main/webapp/index.jsp
  tasks:
    - name: Clone git repo
      git: repo={{ repo }} dest={{ repo_path }} force=yes

    - name: LineInFile example
      lineinfile:
        path: "{{ repo_path }}/{{ file_to_change }}"
        regexp: "<h1>(.*)</h1>"
        line: "<h1>Built on {{ ansible_lsb.description }} with Jenkins</h1>"

    - name: Ensure previously built artifact is absent
      file: path={{ war_path }} state=absent

    - name: Start Maven container and build artifact
      docker_container:
        name: builder
        image: public.ecr.aws/docker/library/maven:3.6-openjdk-8
        volumes:
          "{{ repo_path }}:/git"
        command: mvn -f /git/pom.xml clean package
        restart: yes
        detach: no

    - name: Ensure newly built artifact is present
      file: path={{ war_path }}

    - name: Copy Dockerfile to Build-node
      copy: src=files/Dockerfile dest={{ repo_path }}

    - name: Login to Docker registry
      docker_login:
        registry: "{{ hostvars.localhost.repo_facts.repository.repositoryUri }}"
        username: AWS
        password: "{{ hostvars.localhost.repo_password.stdout }}"
        reauthorize: true

    - name: Build production image and push it to Docker registry
      docker_image:
        name: "{{ hostvars.localhost.repo_facts.repository.repositoryUri }}"
        source: build
        build:
          path: "{{ repo_path }}"
          args:
            artifact: target/{{ app }}.war
        push: yes

- name: Run the App
  hosts: run
  become: yes
  tasks:
    - name: Remove old container
      docker_container:
        name: run
        state: absent

    - name: Remove old image
      docker_image:
        name: "{{ app_image }}"
        state: absent

    - name: Login to Docker registry
      docker_login:
        registry: "{{ hostvars.localhost.repo_facts.repository.repositoryUri }}"
        username: AWS
        password: "{{ hostvars.localhost.repo_password.stdout }}"
        reauthorize: true

    - name: Run app container at production server
      docker_container:
        name: run
        image: "{{ hostvars.localhost.repo_facts.repository.repositoryUri }}"
        ports: "8080:8080"
        recreate: yes

    # Print the app url
    - debug:
        msg: "http://{{inventory_hostname}}:8080/hello-1.0"